apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/armin/pvfolder"
